version: '3'
services:
  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=*YourPassword*
      - MYSQL_DATABASE=*YourDB*
      - MYSQL_USER=*YourUser*
      - MYSQL_PASSWORD=*YourPassword*

      
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - :80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=*YourUser*
      - WORDPRESS_DB_PASSWORD=*YourPassword*
      - WORDPRESS_DB_NAME=*YourDB*
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
volumes:
  db_data:
  wp_data: