---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - assets:/www/assets
    ports:
      - 8081:8080
    user: 1001:1001 # default
    environment:
      - INIT_ASSETS=0 # default
volumes:
    assets: